### ISSUE TITLE
Compile and measure the performance of the Boehm GC 

### ISSUE THREAD

**Issue by mbebenita** [mozilla/pluotsorbet#1542]
I'd like to figure out if running a GC on the phone is feasible. The Boehm GC might be to heavyweight, but it's worth a try. Alon recommended we try the Boehmn GC before looking at other solutions.

**Comment by mbebenita** [comment]
I tried compiling the stable `7.2` release with emscripten, using

```
emconfigure ./configure --without-threads --disable-threads __emscripten__=1 EMSCRIPTEN=1
emmake make
emcc -I .libs/libgc.dylib loop.cpp -s NO_EXIT_RUNTIME=1 -o loop.js
```

I also had to add an entry in `gconfig.h`:

```
# if defined(__emscripten__)
#    define EMSCRIPTEN
#    define I386
#    define mach_type_known
# endif
```
which is pretty much a copy of `__native_client__` configuration.

The `loop.cpp` file is the example from http://www.hboehm.info/gc/simple_example.html

It appears to run, however it has a different output than natively compiled code, the GC doesn't appear to be kicking in. /cc @kripken since he has a lot more experience building with emscripten.

**Comment by kripken** [comment]
I downloaded the latest stable from that site, `7.2f`. Maybe different from your `7.2`? I had to change a few things in your instructions:

The config file that needed editing was  `gcconfig.h` (two `c`s), and I needed

````
# if defined(__EMSCRIPTEN__)
#    define I386
#    define mach_type_known
#    define DATASTART 8
#    define STACK_GROWS_UP
# endif
````

there (datastart 8 is basically where our heap starts: first 8-byte aligned address above 0).

I also had to modify the top of `mach_dep.c` to

````
#if defined(OS2) || defined(CX_UX) || defined(__CC_ARM) || defined(__EMSCRIPTEN__)
````

so it uses `setjmp` and not `_setjmp`.

With all that in place I could build with `emcc -Iinclude/ .libs/libgc.so loop.cpp  -o loop.js`. It runs for a very long time. Reducing the constants there, and adding more prints, i see nothing odd. It just seems like a huge amount of computation.

**Comment by mbebenita** [comment]
Thanks, this appears to be working. I created a new repo and applied your changes: http://github.com/mbebenita/Boehm.js

**Comment by marco-c** [comment]
I've tried to compile and run a couple of tests from Boehm.
```c
#define COUNT 10000000

int main(void) {
  int i;
  unsigned long last_heap_size = 0;

  GC_INIT();

  for (i = 0; i < COUNT; i++) {
    printf("%d\n", i);

    int **p = GC_MALLOC(sizeof(int *));
    int *q = GC_MALLOC_ATOMIC(sizeof(int));

    if (p == 0 || *p != 0) {
      fprintf(stderr, "GC_malloc returned garbage (or NULL)\n");
      exit(1);
    }

    *p = GC_REALLOC(q, 2 * sizeof(int));

    if (i % 10 == 0) {
      unsigned long heap_size = (unsigned long)GC_get_heap_size();
      if (heap_size != last_heap_size) {
        printf("Heap size: %lu\n", heap_size);
        last_heap_size = heap_size;
      }
    }
  }
  return 0;
}
```
This one is failing with the following exception:
```
Duplicate large block deallocation
uncaught exception: abort() at jsStackTrace@tests/realloc_test.js:1152:13
stackTrace@tests/realloc_test.js:1169:22
abort@tests/realloc_test.js:31467:44
_abort@tests/realloc_test.js:1771:7
_GC_abort@tests/realloc_test.js:18213:3
_GC_freehblk@tests/realloc_test.js:7926:3
_GC_free@tests/realloc_test.js:12905:3
_GC_realloc@tests/realloc_test.js:13165:4
_main@tests/realloc_test.js:20836:10
asm._main@tests/realloc_test.js:29569:8
callMain@tests/realloc_test.js:31333:15
doRun@tests/realloc_test.js:31391:42
run@tests/realloc_test.js:31405:5
@tests/realloc_test.js:31491:1
```

```c
int main(void) {
    int *p[10];
    int i;
    GC_set_find_leak(1); /* for new collect versions not compiled       */
                         /* with -DFIND_LEAK.                           */

    GC_INIT();  /* Needed if thread-local allocation is enabled.        */
                /* FIXME: This is not ideal.                            */
    for (i = 0; i < 10; ++i) {
        p[i] = malloc(sizeof(int)+i);
    }
    CHECK_LEAKS();
    for (i = 1; i < 10; ++i) {
        free(p[i]);
    }
    for (i = 0; i < 9; ++i) {
        p[i] = malloc(sizeof(int)+i);
    }
    CHECK_LEAKS();
    CHECK_LEAKS();
    CHECK_LEAKS();
    return 0;
}
```

This one prints:
`Leaked composite object at 0x533fe8 (tests/leak_test.c:12, sz=4, NORMAL)`

**Comment by brendandahl** [comment]
> Leaked composite object at 0x533fe8 (tests/leak_test.c:12, sz=4, NORMAL)

This is expected though right?
http://hboehm.info/gc/leak.html

**Comment by marco-c** [comment]
> This is expected though right?
http://hboehm.info/gc/leak.html

Yes. I've just tried a couple other tests and they're running successfully as well.

**Comment by marco-c** [comment]
I've built a new (failing) test which asserts that an allocated object gets collected: https://github.com/marco-c/Boehm.js/blob/master/tests/finalizer.cpp

The fix for the finalizer test (which I haven't pushed yet), appears to fix the realloc test as well.

**Comment by marco-c** [comment]
https://github.com/mozilla/j2me.js/pull/1612 is re-enabling allocations via Boehm. Obviosuly we need to fix https://github.com/mozilla/j2me.js/issues/1582 in order to make garbage collection actually work

**Comment by marco-c** [comment]
We're now using Boehm (https://github.com/mozilla/pluotsorbet/pull/1731 enabled it for some objects, now it's enabled for almost everything).

**Comment by catmando** [comment]
@marco-c so is the conclusion that it works, and performance is reasonable?

**Comment by marco-c** [comment]
> @marco-c so is the conclusion that it works, and performance is reasonable?

Yes! Are you planning to use it for another project?
