### ISSUE TITLE
Completely remove the long library.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/pluotsorbet#1581]
The only use of it right now is to convert from doubles to longs:

```typescript
  export function numberToLong(v: number): number {
    // TODO Extract logic from Long so we don't allocate here.
    var long = Long.fromNumber(v);
    tempReturn0 = long.high_;
    return long.low_;
  }
```

**Comment by mykmelez** [comment]
We were also using it in the string.js to convert a long to a string, although that is currently commented out:

```JS
//Native["java/lang/StringBuffer.append.(J)Ljava/lang/StringBuffer;"] = function(l, h) {
//  return stringBufferAppend.call(this, Long.fromBits(l, h).toString());
//};
```

**Comment by mbebenita** [comment]
I think we're using it in several places, not just `numberToLong`, but we should funnel everything through `numberToLong` and then remove the library.

The string code is all self hosted now. If we want fast long to string, we can probably pull out the logic for `toString`.

**Comment by marco-c** [comment]
I think this was done in the intex-jit branch, please re-open if I'm wrong.
