### ISSUE TITLE
Design an object layout.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/pluotsorbet#1582]
At the moment we represent Java objects as JS objects with a single property:

```java
class Point {
  int x;
  int y;
}
Point p = new Point();
p.x = p.y = 2;
```

The above code is compiled to:

```javascript
function Point() {
  this._address = ASM._gcMalloc(8);
}
var p = new Point();
i32[p._address + 0 >> 2] = 2;
i32[p._address + 4 >> 2] = 2;
```

We will need to get rid of JS objects altogether, so we will need to come up with an object layout and change the rest of the VM to understand it.

```javascript
var p = ASM._gcMalloc(12);
i32[p + 0 >> 2] = PointKlassID;
i32[p + 4 >> 2] = 2;
i32[p + 8 >> 2] = 2;
```

To make this change, we'll:
1. Need a way bi-directional Klass <--> ID map, this way we can reuse much of the current runtime infrastructure.
2. Update all natives to accept the receiver object as the first argument instead of being passed in implicitly as `this`. 
3. Update all natives to use object handlers. This will make it more difficult to write natives. I propose we build a object handle scheme, or (maybe use typed objects?).

```javascript
function add(point: number /* Point */, ...) {
  var pointHandle = Point.aquire(point);
  var returnValue =  pointHandle.x + pointHandle.y; // These will be getters.
  point.release(); // Release handle object.
  return returnValue;
}
```

**Comment by mykmelez** [comment]
I've started to look at this, but it's a bit complex, since the object assumption is embedded all over the VM, not only in natives, but also in properties like Context.thread, Runtime.isolate, etc. I've been looking for an intermediate step that doesn't require updating every reference simultaneously, but there doesn't seem to be any.

> 2. Update all natives to accept the receiver object as the first argument instead of being passed in implicitly as this.
> 3. Update all natives to use object handlers. This will make it more difficult to write natives. I propose we build a object handle scheme, or (maybe use typed objects?).

Would it be possible to reuse the Klass constructors as object handlers, if we modify them to accept an existing address instead of allocating memory anew?

function add(point: number /* Point */, ...) {
  var pointHandle = new Point(point); // pointHandle._address = point;
  var returnValue =  pointHandle.x + pointHandle.y; // These will be getters.
  // Do we need to release the handle object?
  return returnValue;
}

My other thought was to use a JavaScript Proxy to create a handle that don't require eager definition of getters/setters. In theory, we could even create these in the interpreter and pass them to natives as their *this* object, to avoid having to update the natives. Unsure if this approach is really viable.

**Comment by mykmelez** [comment]
I did some more research on this, also looking at how other VMs work. The [JVM spec](https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-2.html) is intentionally vague, so as not to constrain our creativity:

>Chapter 2. The Structure of the Java Virtual Machine
>
>To implement the Java Virtual Machine correctly, you need only be able to read the class file format and correctly perform the operations specified therein. Implementation details that are not part of the Java Virtual Machine's specification would unnecessarily constrain the creativity of implementors. For example, the memory layout of run-time data areas, the garbage-collection algorithm used, and any internal optimization of the Java Virtual Machine instructions (for example, translating them into machine code) are left to the discretion of the implementor. 
…
>2.7. Representation of Objects
>
>The Java Virtual Machine does not mandate any particular internal structure for objects.
>
>In some of Oracle’s implementations of the Java Virtual Machine, a reference to a class instance is a pointer to a handle that is itself a pair of pointers: one to a table containing the methods of the object and a pointer to the Class object that represents the type of the object, and the other to the memory allocated from the heap for the object data. 

I haven't found first-party descriptions of Sun's JVM, but others have described it (and other JVM implementations) online, including [this blog post](http://www.codeinstructions.com/2008/12/java-objects-memory-structure.html):

> In the Sun JVM, every object (except arrays) has a 2 words header. The first word contains the object's identity hash code plus some flags like lock state and age, and the second word contains a reference to the object's class. Also, any object is aligned to an 8 bytes granularity.

[Code Tools: jol](http://openjdk.java.net/projects/code-tools/jol/) and [
Java Object Size Calculations in 64-bit](http://btoddb-java-sizing.blogspot.com/) also contain useful info.

Currently, we lay out fields in the order in which they're declared (or parsed from the class file). Other JVMs rearrange fields. They also align them and pad them to maintain the alignment. But it isn't clear that we need to do any of that.

We do, however, need a header with enough space for the class ID, and perhaps some other information. The commonest header size seems to be 8 bytes, although [What Heap Dumps Are Lying To You About](http://shipilev.net/blog/2014/heapdump-is-a-lie/) says the HotSpot JVM employs a variable header size of 8, 12, or 16 bytes.

I've been experimenting with a 4-byte header (just enough for the class ID) over in https://github.com/mykmelez/j2me.js/tree/intex-object. It doesn't quite work yet, though. And we'll probably want to expand it to store other info, like the lock state.

**Comment by mbebenita** [comment]
> Other JVMs rearrange fields.

We do need to make sure subclasses don't rearrange fields. It might make sense to align all doubles to 16 byte boundaries so that we can read them through a Float64 view.

**Comment by marco-c** [comment]
I guess we can close this now.
