### ISSUE TITLE
Integrate the Boehm GC.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/pluotsorbet#1583]
PR #1542 adds the GC to the source tree but we don't actually use it yet. We disabled it because it was causing some correctness issues that we never had time to work out. We should re-enable it.

I've never used it before, so we need someone to learn how it works and find a way to integrate it. At a minimum, this will probably depend on #1582.

**Comment by marco-c** [comment]
A few of the latest updates to Boehm.js and https://github.com/mozilla/j2me.js/pull/1612 should fix the correctness issues we were seeing.

**Comment by marco-c** [comment]
There are three ways in which we could use the Boehm GC.

# GC_malloc

This is the basic method, where the entire area of memory allocated is scanned for pointers (so it's also the slowest method). It could be used in conjunction with GC_malloc_atomic (for allocating memory that doesn't contain pointers, for example primitive arrays).

# GC_malloc_explicitly_typed

This method allows you to specify a descriptor for the object to be allocated, allowing you to specify which fields are references and which are values. This allows the collector to avoid scanning the entire object.

```
struct obj {
  int* pointer1;
  int* value1;
  int* pointer2;
};

GC_word obj_bitmap[GC_BITMAP_SIZE(obj)] = { 0 };
GC_set_bit(obj_bitmap, GC_WORD_OFFSET(obj, pointer1));
GC_set_bit(obj_bitmap, GC_WORD_OFFSET(obj, pointer2));
GC_descr obj_descr = GC_make_descriptor(obj_bitmap, GC_WORD_LEN(obj));

obj* an_obj = (obj*)GC_MALLOC_EXPLICITLY_TYPED(sizeof(obj), obj_descr);
```

# GC_gcj_malloc

This works like GC_malloc_explicitly_typed, but it's been designed to work with the GCJ data structures.
In this case:
 - The first word of the allocated object contains a pointer to a structure describing the object's type (vtable)
 - The structure contains a descriptor (similar to what you use with GC_malloc_explicitly_typed) at a certain offset

```
struct obj_vtable {
  void* ptr; // in GCJ this is a pointer to a class
  GC_word descr; // Bitmap (or another kind of descriptor) describing the object's fields
  ...
};

struct obj_vtable my_obj_vtable = {
  0,
  0xXXXX
};

struct my_obj {
  struct obj_vtable* vtable;
  int* pointer;
  int value;
  ...
};

my_obj* an_obj = (my_obj*)GC_GCJ_MALLOC(sizeof(my_obj), &my_obj_vtable);
```

There are several ways to define a descriptor (bitmap, length and probably others). If we don't want to rearrange fields, then the bitmap is probably the best option.

**Comment by marco-c** [comment]
The GC has been integrated with some recent PRs (the first being https://github.com/mozilla/pluotsorbet/pull/1731). I've opened https://github.com/mozilla/pluotsorbet/issues/1745 to investigate using the typed versions of malloc.
