### ISSUE TITLE
TestBouncyCastleSHA256 test fails due to unresponsive script

### ISSUE THREAD

**Issue by mykmelez** [mozilla/pluotsorbet#1629]
If I merge master into the intex branch, then the new TestBouncyCastleSHA256 test fails due to an unresponsive script:

> 1.2:1.5  | Running com.sun.midp.crypto.TestBouncyCastleSHA256 
> FAIL unresponsive Script: http://localhost:8000/bld/j2me.js:2022

The test hangs my desktop browser too, although not long enough to trigger the test failure.

**Comment by marco-c** [comment]
This would probably be fixed by re-enabling the compiler.

**Comment by marco-c** [comment]
Indeed, it's no longer failing now.
