### ISSUE TITLE
J2ME Trademark

### ISSUE THREAD

**Issue by DonaldOJDK** [mozilla/pluotsorbet#1645]
Hi,

Full disclosure that although I am not responsible for Java ME related technology, I do run the Java SE Product Management team at Oracle.  I was asked by a colleague of mine to open an issue here regarding the name of this project.  Please note that J2ME is a trademark of Oracle Corporation and there is potential for confusion as a result.  We're happy to discuss either via the issue tracker or on a call with whomever was relevant to the discussion.

Cheers.

**Comment by mykmelez** [comment]
Thanks for bringing this up. I've raised it with our legal team, and I'm waiting to hear back from them.

**Comment by mykmelez** [comment]
I've changed the repo name.  Please contact Mozilla's legal team if you have any further concerns (legal-notices@mozilla.com).
