### ISSUE TITLE
Where are the images saved in Whatsapp?

### ISSUE THREAD

**Issue by gmarty** [mozilla/pluotsorbet#1675]
When I open an image that a contact sent me, I can open a web activity on long press that offers me to save the image. However, this is not clear where is the image saved, as I can't see it in the gallery app.

Not sure if that changes anything, but my default media location is the SD card.

**Comment by marco-c** [comment]
At the moment we're storing files in a virtual FS on top of IndexedDB. To save them to the phone FS we'd need to fix https://github.com/mozilla/pluotsorbet/issues/1282.

**Comment by marco-c** [comment]
https://github.com/mozilla/pluotsorbet/issues/1688
