### ISSUE TITLE
WhatsApp update isn't working

### ISSUE THREAD

**Issue by gmarty** [mozilla/pluotsorbet#1693]
Whatsapp indicates that there is an update available.
Is there a way I can apply the update without loosing all my chat history?

**Comment by marco-c** [comment]
The update shouldn't clear your chat history, unless there's a bug in pluotsorbet.

**Comment by gmarty** [comment]
My question was more "is there a way to apply the update?". Taping the update button triggers a loader but nothing happens and the update notification is still present.

**Comment by marco-c** [comment]
@gmarty I forgot, but the update is applied when you close WhatsApp (press the "Hide" button). Can you try if it works for you?
We'll make it less confusing in https://github.com/mozilla/pluotsorbet/issues/1716.

**Comment by gmarty** [comment]
Yes, I confirm the update starts when clicking on the Hide button. Thanks!
