### ISSUE TITLE
build fails in TestIsolate with "Same number of lines output."

### ISSUE THREAD

**Issue by mykmelez** [mozilla/pluotsorbet#1698]
@marco-c https://travis-ci.org/mozilla/pluotsorbet/builds/69201730 failed with "Same number of lines output." Could that be a regression from #1684?

**Comment by marco-c** [comment]
The difference in the output is this line: "3.2:3.5  | 10: 3 isolates6 0 2 m2 ". For some reason the two lines are printed on the same line.

**Comment by mykmelez** [comment]
Reverting #1684 fixes this locally, so I'm going to revert it.

**Comment by mykmelez** [comment]
Fixed by #1702.
