### ISSUE TITLE
Frame adapter monitors broken.

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pluotsorbet#1734]
``` frame.monitor = getMonitor(monitor); // XXX This doesn't seem to be used; delete? ```
The above and the code for the getter/setter was removed. This will break synchronized frame adapters because we have to store the monitor so we can unlock it when we return from the method.  It appears unused because when it is read we do not use the getter (see int.ts ARETURN)
``` $.ctx.monitorExit(getMonitor(i32[fp + FrameLayout.MonitorOffset]));```

**Comment by mykmelez** [comment]
@marco-c We should revert the change that broke this.

**Comment by brendandahl** [comment]
Probably not an issue until the compiler is enabled again.

**Comment by marco-c** [comment]
Fixed in https://github.com/mozilla/pluotsorbet/pull/1762.
