### ISSUE TITLE
Enabling compiler with intex.

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pluotsorbet#1743]
Work in https://github.com/brendandahl/j2me.js/tree/intex-bailouts

General Info:
- More marker frame types: There's a comment in endUnwind to explain some of this more, but in general we use a Native marker frame to delineate when we enter native code (compiled or hand written natives). We also use a special interrupt frame to delineate when code was called from a non-call site (e.g. static initializers).
- Natives must bailout:
Any native code that yields must handle bailouts in the same way that compiled code does.

```javascript
    if (U) {
      $.nativeBailout(Kind.Void);
    }
```
- Long objects are removed to make things easier.
- Longs and Doubles are now passed around as multiple slots and as their integer representation (and floats).
- New flag for the shell: `-m=<number of methods to compile>`. This helps with debugging ALOT. If the test is working with the interpreter, find the number of methods to compile where the tests start failing then look at the compiled code for that method. (To see what is compiled use -w=j).

Work before merge:
- Merge upstream intex
- Merge klass removal
- Fix method invocation by using getLinkedMethod or something similar

Post merge work:
- Add long/double support
- Optimize when methods get compiled/linked.
- Re-enable OSR - This was kind of working at one point. There is currently code to OSR in Bytecodes.GOTO under special circumstances.
- Re-enable preemption
- Profile

**Comment by marco-c** [comment]
Enabled in #1833.
