### ISSUE TITLE
TestHttpsConnection-0: fail [length is > 0]

### ISSUE THREAD

**Issue by mykmelez** [mozilla/pluotsorbet#1749]
On my Mac, on the intex branch, I now consistently see a failure in TestHttpsConnection when running tests via `make test`:

>1.2:1.5  | Running javax.microedition.io.TestHttpsConnection 
>1.2:1.5  | javax.microedition.io.TestHttpsConnection-0: fail [length is > 0] 
>127.0.0.1 - - [20/Jul/2015 16:56:53] "GET /test.html HTTP/1.1" 200 -
>1.2:1.5  | javax.microedition.io.TestHttpsConnection: 4 pass, 1 fail, 0 known fail, 0 unknown pass 
>1.2:1.5  | javax.microedition.io.TestHttpsConnection: test expected 5 passes, got 4 
>1.2:1.5  | javax.microedition.io.TestHttpsConnection: test expected 0 failures, got 1 
>1.2:1.5  | javax.microedition.io.TestHttpsConnection: class fail 

I don't see this when I run just the javax.microedition.io.TestHttpsConnection test in a browser, however.

**Comment by marco-c** [comment]
@mykmelez can you still reproduce? I can't on my Mac.

**Comment by mykmelez** [comment]
I can't reproduce this either anymore.
