### ISSUE TITLE
org.mozilla.gc.TestRuntime-4: fail [Free memory increases after a collection] 

### ISSUE THREAD

**Issue by mykmelez** [mozilla/pluotsorbet#1772]
Builds for both #1763 and #1771 have failed with this error:

>1.2:1.5  | Running org.mozilla.gc.TestRuntime 
>1.2:1.5  | freeMemory1: 122896384 
>1.2:1.5  | freeMemory2: 122159104 
>1.2:1.5  | freeMemory3: 122159104 
>1.2:1.5  | org.mozilla.gc.TestRuntime-4: fail [Free memory increases after a collection] 
>1.2:1.5  | org.mozilla.gc.TestRuntime: 4 pass, 1 fail, 0 known fail, 0 unknown pass 
>1.2:1.5  | org.mozilla.gc.TestRuntime: test expected 5 passes, got 4 
>1.2:1.5  | org.mozilla.gc.TestRuntime: test expected 0 failures, got 1 
>1.2:1.5  | org.mozilla.gc.TestRuntime: class fail 

Builds:

https://travis-ci.org/mozilla/pluotsorbet/builds/72920166
https://travis-ci.org/mozilla/pluotsorbet/builds/72920347

**Comment by mykmelez** [comment]
This failed again on the merge commit for c146d91, so it looks like that change doesn't fix this problem (or at least not reliably):

https://travis-ci.org/mozilla/pluotsorbet/builds/73240595

**Comment by marco-c** [comment]
This should be fixed now by https://github.com/mozilla/pluotsorbet/pull/1776.
