### ISSUE TITLE
Static field access is 6X slower than instance fields.

### ISSUE THREAD

**Issue by mbebenita** [mozilla/pluotsorbet#1791]
Running `benchmark.Fields` on latest intex branch prints:

```
static int: 441
static long: 443
static float: 426
static double: 419
int: 64
long: 71
float: 57
double: 75
```

The performance of static fields is very poor, nearly 6X slower than instance fields. Static fields are more complicated to deal with because we need to look up the static class object. This is currently done through a call to `$.SA()` which converts the `classId` into a `ClassInfo` objects, then calls `getStaticObjectAddress` which then uses the class `mangledName` to cache the class static object address in a table called `staticObjectAddresses`. 

```javascript
function SA(classId: number) {
  return this.getStaticObjectAddress(classIdToClassInfoMap[classId]);
}
```

I don't see any reason for using the `mangledName` to lookup class objects. Why can't we just use the `classId` directly?

```
i32[($.staticObjectAddresses[14] || $.SA(14))+16>>2]=A;
```

**Comment by marco-c** [comment]
Done in the intex-jit branch.
