### ISSUE TITLE
unsetUncollectable(addr: number) should assert

### ISSUE THREAD

**Issue by mbebenita** [mozilla/pluotsorbet#1824]
We should assert that the address that is no longer uncollectable is what we expect.

```typescript
export function unsetUncollectable(addr: number) {
  i32[(uncollectableAddress >> 2) + uncollectableNumber] = 0;
  uncollectableNumber--;
}
```

Ideally, this code should search for the address in the array and zero it out, not behave like a stack.

**Comment by marco-c** [comment]
Fixed in #1828.
