### ISSUE TITLE
UMD Research Study

### ISSUE THREAD

**Issue by UMD-study** [mozilla/pluotsorbet#1876]
Hi there,
We are researchers from the University of Maryland conducting a study about software code reuse. If you are interested in helping us in this study​ through ​a short interview about this project, please contact us on ​software-reuse-study@cs.umd.edu​ for more information​. You will be ​compensated for your time.

Thanks
Ahmed

**Comment by mykmelez** [comment]
I previously received an email message about this study, and I've now responded by email. Let's continue the discussion there.
